DELETE http://localhost:3000/api/persons/1106
###
GET http://localhost:3000/api/persons/1


###
GET http://localhost:3000/api/persons

###
GET https://phonebookbackend-xohj.onrender.com/api/persons

###
POST https://phonebookbackend-xohj.onrender.com/api/persons
content-type: application/json

{
    "name": "Germa Granacho", 
    "number": "39-23-6423122"    
}



###
POST http://localhost:3000/api/persons
content-type: application/json

{
    "name": "germanida garnacho", 
    "number": "39-23-6423122"    
}

###
DELETE http://localhost:3000/api/person/456

###
GET http://localhost:3000/api/personsonas
